feat: implement ProductManager & Product class
M-0923/wad203-mid-term-project-fake-store-snowperson pull request #11
Opened 2024-01-23 06:32 UTC by KaiKoide

## Overview

- Implement ProductManager & Product classes.
- Call ProductManager class and push the product data to the array after fetch the data in `index.js`.

## Changes

- Implement ProductManager class
- Implement Product class
- Fetch the product data

## Review points

- What should the reviewer look at?

## Notes

- Any additional context or things to note

## Assignee Checklist:

- [ ] The base branch is correct (no accidental merges)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors in the console

## Reviewer Checklist

- [ ] Code readability and simplicity
- [ ] Follows best practices and coding standards
- [ ] Understandable and maintainable code

2024-01-23 18:10 UTC, akiomatic requested changes

2024-01-23 18:10 UTC, akiomatic commented on src/js/components/Product.js
> +   */
Thank you for writing JSDoc, but I would like to suggest a minor formatting change for better clarity and consistency by separating the documentation for each property. Here's how it would look after the change:

```
/**
 * @type {number}
 */
#id;

/**
 * @type {string}
 */
#title;

// ... and similarly for the other properties.
```

2024-01-23 18:10 UTC, akiomatic commented on src/js/components/Product.js
> +  #img;
Could you add getter methods for each private field?

2024-01-23 18:10 UTC, akiomatic commented on src/js/components/ProductManager.js
Could you add a getter method for `#productList` and implement a method to retrieve a product by its id?

2024-01-23 18:10 UTC, akiomatic commented on src/js/components/ProductManager.js
> +   * @type {object[ ]} #productList
I think the `object[]` needs to be replaced with `Product[]` because the `#productList` is the array of `Product`.

2024-01-23 18:10 UTC, akiomatic commented on src/js/components/ProductManager.js
> +   * @param {object} product
So does the `#productList`. This `addProduct` method will receive `Product`, not `object`.
Also, could you add a brief explanation of what this method does in the document?

2024-01-23 18:10 UTC, akiomatic commented on src/js/index.js
> +   * @return {object[]} productData
I think the `object[]` should be `Promise<Object[]>`, and the `@return` should be `@returns`.
Additionally, I would be grateful if you could include a description of the `fetchData` method.

2024-01-23 18:10 UTC, akiomatic commented on src/js/index.js
> +    data.map((productData) => {
I think you should use the `.forEach()` rather than`.map()`.

2024-01-24 00:23 UTC, KaiKoide commented
I have modified the codes in the mentioned parts.

2024-01-24 00:26 UTC, akiomatic approved these changes
LGTM! Thank you!

2024-01-24 00:28 UTC, merged